export interface Language { code: string; name: string; native: string; flag: string; rtl?: boolean; }
const L = (code: string, name: string, native: string, flag: string, rtl?: boolean): Language => ({ code, name, native, flag, ...(rtl ? { rtl } : {}) });
export const LANGUAGES: Language[] = [
  L("en","English","English","🇬🇧"),L("es","Spanish","Español","🇪🇸"),L("fr","French","Français","🇫🇷"),
  L("de","German","Deutsch","🇩🇪"),L("it","Italian","Italiano","🇮🇹"),L("pt","Portuguese","Português","🇵🇹"),
  L("ru","Russian","Русский","🇷🇺"),L("zh-CN","Chinese (Simplified)","简体中文","🇨🇳"),L("zh-TW","Chinese (Traditional)","繁體中文","🇹🇼"),
  L("ja","Japanese","日本語","🇯🇵"),L("ko","Korean","한국어","🇰🇷"),L("hi","Hindi","हिन्दी","🇮🇳"),
  L("ar","Arabic","العربية","🇸🇦",true),L("bn","Bengali","বাংলা","🇧🇩"),L("ur","Urdu","اردو","🇵🇰",true),
  L("tr","Turkish","Türkçe","🇹🇷"),L("vi","Vietnamese","Tiếng Việt","🇻🇳"),L("th","Thai","ไทย","🇹🇭"),
  L("id","Indonesian","Bahasa Indonesia","🇮🇩"),L("ms","Malay","Bahasa Melayu","🇲🇾"),L("fil","Filipino","Filipino","🇵🇭"),
  L("nl","Dutch","Nederlands","🇳🇱"),L("sv","Swedish","Svenska","🇸🇪"),L("no","Norwegian","Norsk","🇳🇴"),
  L("da","Danish","Dansk","🇩🇰"),L("fi","Finnish","Suomi","🇫🇮"),L("pl","Polish","Polski","🇵🇱"),
  L("cs","Czech","Čeština","🇨🇿"),L("sk","Slovak","Slovenčina","🇸🇰"),L("hu","Hungarian","Magyar","🇭🇺"),
  L("ro","Romanian","Română","🇷🇴"),L("bg","Bulgarian","Български","🇧🇬"),L("el","Greek","Ελληνικά","🇬🇷"),
  L("uk","Ukrainian","Українська","🇺🇦"),L("he","Hebrew","עברית","🇮🇱",true),L("fa","Persian","فارسی","🇮🇷",true),
  L("ta","Tamil","தமிழ்","🇮🇳"),L("te","Telugu","తెలుగు","🇮🇳"),L("mr","Marathi","मराठी","🇮🇳"),
  L("gu","Gujarati","ગુજરાતી","🇮🇳"),L("kn","Kannada","ಕನ್ನಡ","🇮🇳"),L("ml","Malayalam","മലയാളം","🇮🇳"),
  L("pa","Punjabi","ਪੰਜਾਬੀ","🇮🇳"),L("ne","Nepali","नेपाली","🇳🇵"),L("si","Sinhala","සිංහල","🇱🇰"),
  L("my","Burmese","မြန်မာ","🇲🇲"),L("km","Khmer","ខ្មែរ","🇰🇭"),L("lo","Lao","ລາວ","🇱🇦"),
  L("mn","Mongolian","Монгол","🇲🇳"),L("ka","Georgian","ქართული","🇬🇪"),L("hy","Armenian","Հայերեն","🇦🇲"),
  L("az","Azerbaijani","Azərbaycanca","🇦🇿"),L("kk","Kazakh","Қазақша","🇰🇿"),L("uz","Uzbek","Oʻzbekcha","🇺🇿"),
  L("sw","Swahili","Kiswahili","🇰🇪"),L("am","Amharic","አማርኛ","🇪🇹"),L("zu","Zulu","isiZulu","🇿🇦"),
  L("af","Afrikaans","Afrikaans","🇿🇦"),L("sq","Albanian","Shqip","🇦🇱"),L("eu","Basque","Euskara","🇪🇸"),
  L("be","Belarusian","Беларуская","🇧🇾"),L("bs","Bosnian","Bosanski","🇧🇦"),L("ca","Catalan","Català","🇪🇸"),
  L("hr","Croatian","Hrvatski","🇭🇷"),L("et","Estonian","Eesti","🇪🇪"),L("gl","Galician","Galego","🇪🇸"),
  L("is","Icelandic","Íslenska","🇮🇸"),L("ga","Irish","Gaeilge","🇮🇪"),L("lv","Latvian","Latviešu","🇱🇻"),
  L("lt","Lithuanian","Lietuvių","🇱🇹"),L("mk","Macedonian","Македонски","🇲🇰"),L("mt","Maltese","Malti","🇲🇹"),
  L("sr","Serbian","Српски","🇷🇸"),L("sl","Slovenian","Slovenščina","🇸🇮"),L("cy","Welsh","Cymraeg","🇬🇧"),
  L("yo","Yoruba","Yorùbá","🇳🇬"),L("ig","Igbo","Igbo","🇳🇬"),L("ha","Hausa","Hausa","🇳🇬"),
  L("so","Somali","Soomaali","🇸🇴"),L("xh","Xhosa","isiXhosa","🇿🇦"),L("hmn","Hmong","Hmoob","🇱🇦"),
  L("jv","Javanese","Basa Jawa","🇮🇩"),L("su","Sundanese","Basa Sunda","🇮🇩"),L("ku","Kurdish","Kurdî","🇮🇶"),
  L("ps","Pashto","پښتو","🇦🇫",true),L("sd","Sindhi","سنڌي","🇵🇰",true),L("tg","Tajik","Тоҷикӣ","🇹🇯"),
  L("tk","Turkmen","Türkmençe","🇹🇲"),L("ky","Kyrgyz","Кыргызча","🇰🇬"),L("tt","Tatar","Татарча","🇷🇺"),
  L("as","Assamese","অসমীয়া","🇮🇳"),L("or","Odia","ଓଡ଼ିଆ","🇮🇳"),L("kok","Konkani","कोंकणी","🇮🇳"),
  L("sa","Sanskrit","संस्कृतम्","🇮🇳"),L("mai","Maithili","मैथिली","🇮🇳"),L("bho","Bhojpuri","भोजपुरी","🇮🇳"),
  L("doi","Dogri","डोगरी","🇮🇳"),L("mni","Manipuri","মৈতৈলোন্","🇮🇳"),L("sat","Santali","ᱥᱟᱱᱛᱟᱲᱤ","🇮🇳"),
  L("ny","Chichewa","Chichewa","🇲🇼"),L("rw","Kinyarwanda","Kinyarwanda","🇷🇼"),L("lg","Luganda","Luganda","🇺🇬"),
  L("st","Sesotho","Sesotho","🇱🇸"),L("tn","Setswana","Setswana","🇧🇼"),L("ts","Tsonga","Xitsonga","🇿🇦"),
  L("ve","Venda","Tshivenda","🇿🇦"),L("nr","Ndebele","isiNdebele","🇿🇦"),L("ss","Swati","siSwati","🇸🇿"),
  L("mg","Malagasy","Malagasy","🇲🇬"),L("ht","Haitian Creole","Kreyòl","🇭🇹"),L("haw","Hawaiian","ʻŌlelo Hawaiʻi","🇺🇸"),
  L("mi","Maori","Te Reo Māori","🇳🇿"),L("sm","Samoan","Gagana Samoa","🇼🇸"),L("to","Tongan","Lea Fakatonga","🇹🇴"),
  L("fj","Fijian","Na Vosa Vakaviti","🇫🇯"),L("tet","Tetum","Tetun","🇹🇱"),L("dv","Dhivehi","ދިވެހި","🇲🇻",true),
  L("dz","Dzongkha","རྫོང་ཁ","🇧🇹"),L("bo","Tibetan","བོད་ཡིག","🇨🇳"),L("ug","Uyghur","ئۇيغۇرچە","🇨🇳",true),
  L("lb","Luxembourgish","Lëtzebuergesch","🇱🇺"),L("rm","Romansh","Rumantsch","🇨🇭"),L("fo","Faroese","Føroyskt","🇫🇴"),
  L("kl","Greenlandic","Kalaallisut","🇬🇱"),L("gv","Manx","Gaelg","🇮🇲"),L("gd","Scottish Gaelic","Gàidhlig","🇬🇧"),
  L("br","Breton","Brezhoneg","🇫🇷"),L("co","Corsican","Corsu","🇫🇷"),L("oc","Occitan","Occitan","🇫🇷"),
  L("sc","Sardinian","Sardu","🇮🇹"),L("fur","Friulian","Furlan","🇮🇹"),L("lad","Ladino","Ladino","🇮🇱"),
  L("yi","Yiddish","ייִדיש","🇮🇱",true),L("ckb","Central Kurdish","کوردی","🇮🇶",true),L("eo","Esperanto","Esperanto","🌐"),
  L("la","Latin","Latina","🇻🇦"),L("qu","Quechua","Runasimi","🇵🇪"),L("gn","Guarani","Avañeʼẽ","🇵🇾"),
  L("ay","Aymara","Aymar","🇧🇴"),L("nah","Nahuatl","Nāhuatl","🇲🇽"),L("chr","Cherokee","ᏣᎳᎩ","🇺🇸"),
  L("nv","Navajo","Diné bizaad","🇺🇸"),L("iu","Inuktitut","ᐃᓄᒃᑎᑐᑦ","🇨🇦"),L("cr","Cree","ᓀᐦᐃᔭᐍᐏᐣ","🇨🇦"),
  L("oj","Ojibwe","ᐊᓂᔑᓈᐯᒧᐎᓐ","🇨🇦"),L("pap","Papiamento","Papiamentu","🇨🇼"),L("jam","Jamaican Patois","Patwah","🇯🇲"),
  L("gcf","Guadeloupean Creole","Kréyòl","🇬🇵"),L("tpi","Tok Pisin","Tok Pisin","🇵🇬"),L("bis","Bislama","Bislama","🇻🇺"),
  L("srn","Sranan","Sranantongo","🇸🇷"),L("arc","Aramaic","ܐܪܡܝܐ","🇸🇾"),L("tlh","Klingon","tlhIngan Hol","🖖"),
];
export const DEFAULT_LANGUAGE = LANGUAGES[0];
export const findLanguage = (code: string): Language => LANGUAGES.find((l) => l.code === code) ?? DEFAULT_LANGUAGE;
